import { Flex } from "@chakra-ui/react";
import { motion } from "framer-motion";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { GetServerSidePropsContext } from "next";
import MainContainer from "../../components/profilePage/MainContainer";
import { useRouter } from "next/router";
import userProfile from "@/hooks/userProfile";
import { userState } from "@/atoms/userAtom";
import { query } from "firebase/firestore";


export default function Page() {
  const router = useRouter();

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/header.png" />
      </Head>
      <MainContainer slug={router.query.slug?.toString()} />
    </motion.div>
  );
}
